language: python
python:
  - "2.7"
env:
  - NODE_VERSION="6"
before_install:
  - "nvm install $NODE_VERSION"  # install node.js for example app
  - "pip install virtualenv"
  - "npm install -g phantomjs-prebuilt"  # install phantom-js for e2e tests
install:
  - "npm run --prefix test setup"  # install example app dependencies and test
script:
  - "npm run --prefix test lint"  # lint module and test bundle
  - "npm run --prefix test app:detached"  # start example app
  - "npm run --prefix test test"