language: python
python:
  - "2.7"
env:
  - NODE_VERSION="7"
before_install:
  - "nvm install $NODE_VERSION"  # install node.js for example app
  - "pip install virtualenv"
  - "apt-get install chromium-browser=60"  # install chromium with headless suport
  - "npm install -g chromedriver@2.32.3"  # install chromedriver with headless support
install:
  - "make setup"  # install example app dependencies and test
script:
  - "make app"  # start example app
  - "make tests"  # start lint and e2e tests