language: python
python:
  - "2.7"
env:
  - NODE_VERSION="6"
before_install:
  - "nvm install $NODE_VERSION"  # install node.js for example app
  - "pip install virtualenv"
  - "pip install pylint"
  - "npm install -g phantomjs-prebuilt"  # install phantom-js for e2e tests
install:
  - "npm run --prefix example setup"  # install example app dependencies and test
script:
  - "pylint pyseleniumjs/e2ejs.py --errors-only"  # lint module
  - "npm run --prefix example app:detached"  # start example app
  - "npm run --prefix example test"